[package]
name = "advent2025"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.8.0"
itertools = "0.14.0"
range-set-blaze = "0.4.1"
regex = "1.12.2"

[[bench]]
name = "problems"
harness = false
